### ISSUE TITLE
Efficiently compute the number of accepted registrations on a competition

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-registration#330]
Currently we are querying the DynamoDB using a filter query for _every time we accept a registration_. This is highly inefficient. Instead, we should have somewhere that we're incrementing the number of accepted registrations.

The UX concern here is that as competition size grows, it takes longer for the "Accept Registration" action to complete, making for frustrating experience for an organizer.

## Requirements: 
1. Must be accessible by a distributed system - ie, there's a single source of truth all instances can query, so that we don't accidentally accept too many registrations

## Options: 
1. **Redis**: Increment a counter, this wouldn't persist so the _first_ time the count is requested for a comp (or if the key gets invalidated) it would need to be queried from DynamoDB. 
2. **DynamoDB table**: We would have another table with key of CompID, and value being the number of accepted registrations. Increment/decrement this counter every time a registration is accepted/cancelled. This would persist across system restarts/cache invalidations.
3. **Query directly**: Create an `is_competing` key that is true when the status is `accepted`, and query for a count of registrations with a certain CompID where `is_competing` is `true`

We will go with Option 3 for now. This should work up to ~2000 accepted registrations, because of the DynamoDB query size limit of 1MB. After that we would need to paginate and combine queries.

**Comment by dunkOnIT** [comment]
We'll test the current performance of the frontend when there are a lot of accepted competitors, and based on that determine when an efficiency improvement is necessary.

**Comment by FinnIckler** [comment]
We used redis
