### ISSUE TITLE
More explicit event selection UI

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-registration#501]
Currently, the event selection UI doesn't provide a clear separation between what events a user is/isn't registered for - especially for newcomers in cases where there are limited events.
![image](https://github.com/thewca/wca-registration/assets/52967253/e08c5fe7-ebae-4ba9-84b7-bdc9b9c16787)

My best suggestion (I'm open to others) is clearly demarcated "Registered" / "Not Registered" sections, sort of like the following, with the ability to click on an event to have it move between the rows: 

### Registered

![image](https://github.com/thewca/wca-registration/assets/52967253/bd71beb4-d07d-41e6-a9ac-cd1bc690495a)

### Not Registered

![image](https://github.com/thewca/wca-registration/assets/52967253/7b56c6eb-0178-401d-8445-cd13e302a04e)

**Comment by kr-matthews** [comment]
The new (not yet publicly deployed) competitions page has an improved version of this.
![image](https://github.com/thewca/wca-registration/assets/49137025/4e32d4e2-fe2e-4bba-85eb-0677ad258ff5)

It might be relatively quick and easy to reuse this across the website?

Although ideally we'd be reusing a component from [wca-helpers](https://github.com/thewca/wca-helpers/) here and in the new registration repo.
