### ISSUE TITLE
Refactor mocked/stubbed Monolith API interactions 

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-registration#553]
Currently, if we want to return a mocked response to an API request, it happens all over a number of different `_api.rb` files, which results in some pretty bloated logic.

I think it should be possible to: 
- [ ] extract the logic of whether to return a mocked response into one file (eg, `helpers/wca_api.rb`)
- [ ] introduce a `RETURN_MOCKED_RESPONSES` env variable to be able to toggle the mocked responses (instead of having cased logic that requires a failure to call the mock)
- [ ] determine which mock payload to return based on the URL being called (instead of based on the function being called)

**Comment by Liamhhhhh** [comment]
Mock, you can try [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1), it's a free tool that imports API definitions and automatically generates realistic mock data for testing, enhancing development efficiency with its "Smart Mock" feature. 
﻿ 
﻿

**Comment by dunkOnIT** [comment]
Unnecessary now that the frontend is in the monolith
