### ISSUE TITLE
Bug when organiser registers - changes events - updates registration

### ISSUE THREAD

**Issue by Goosly** [thewca/wca-registration#723]
**Reproduce:**

1. Setup a comp as an organiser with event 3x3 and 4x4
2. Register for both events (new registration system, obviously 😉)
3. Remove 4x4, add 2x2 to the competition events
4. Update your own registration: add 2x2 --> gives an error
![image](https://github.com/user-attachments/assets/360359b8-bffc-42f4-8fcc-d50d9e3a92d4)
Technical note: in the Patch request, the 4x4 is still submitted, even though the competition doesn't have 4x4 anymore

**Expected behavior:**
Step 4 works, the user is registered for 3x3 and 2x2

**Comment by FinnIckler** [comment]
should be fixed now
