### ISSUE TITLE
"Registered on" is incorrect

### ISSUE THREAD

**Issue by beranka** [thewca/wca-registration#737]
All registrations to my competition (https://www.worldcubeassociation.org/competitions/PragueCubeMas2024/edit/registrations) have the value in "registered on" set to 19/11/2024 11:25:xx.000, which is definitely not correct.

**Comment by FinnIckler** [comment]
The issue is that we overwrote the created_at timestamp with the v2-v3 migration, but we still have it in the registration history so we can restore it.

**Comment by FinnIckler** [comment]
this was fixed
