### ISSUE TITLE
[WAITING FOR ENV_VARS CHANGE] Prevent `dynamoid_reset.rb` from nuking any non-test database

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/wca-registration#92]
## Change required: 

Modify https://github.com/thewca/wca-registration/blob/63ac10f52a5a48469715863af33a2a1a44b152bd/app/models/registration.rb#L8 to check for test/dev

## Slack conversation:

Duncan Hobbs
:speech_balloon:  [5:49 PM](https://worldcubeassociation.slack.com/archives/D03FDGJRUCD/p1689004197889209)
dynamoid_reset.rb feels a little dangerous to me:
# frozen_string_literal: true

raise "Tests should be run in 'test' environment only" if Rails.env != 'test' && Rails.env != 'development'

module DynamoidReset
  def self.all
    Dynamoid.adapter.list_tables.each do |table|
      # Only delete tables in our namespace
      if table =~ /^#{Dynamoid::Config.namespace}/
        Dynamoid.adapter.delete_table(table)
      end
    end
    Dynamoid.adapter.tables.clear
    # Recreate all tables to avoid unexpected errors
    Dynamoid.included_models.each { |m| m.create_table(sync: true) }
  end
end

# Reduce noise in test output
Dynamoid.logger.level = Logger::FATAL
Even if someone messes up the env variable in prod somehow, it will only be called if the tests are run. But I'm wondering if there's a better way to prevent the accidental nuke of our production database?

Finn Ickler
  [5:52 PM](https://worldcubeassociation.slack.com/archives/D03FDGJRUCD/p1689004368479919)
I guess we can fix by changing the name of the dynamo table in test
New
[5:54](https://worldcubeassociation.slack.com/archives/D03FDGJRUCD/p1689004478046849)
I am pretty sure this can already not happen because of how the name of the variable is initialised in https://github.com/thewca/wca-registration/blob/63ac10f52a5a48469715863af33a2a1a44b152bd/app/models/registration.rb#L8
[5:55](https://worldcubeassociation.slack.com/archives/D03FDGJRUCD/p1689004535425789)
Ah okay this only checks for staging
[5:55](https://worldcubeassociation.slack.com/archives/D03FDGJRUCD/p1689004546805349)

**Comment by dunkOnIT** [comment]
@FinnIckler suggests we add an `elseif` clause that sets the database name to `registrations-testing` if we're in the test environment

**Comment by FinnIckler** [comment]
fixed by renaming adding an environment variable for the DYNAMO_REGISTRATION_TABLE
